Send messages on events where the marathon appId matches given regex
tobilg/marathon-slack pull request #12
Opened 2017-05-30 20:45 UTC by eodgooch

In a large data-center the operations team would like to be notified of marathon events matching some Regular Expression pattern. This pull request allows users to specify a Marathon env var `APP_ID_REGEXS` which is a comma separated list of strings to filter events by.

2017-05-31 05:35 UTC, tobilg commented
Thanks for the PR! Could you please add an example of the usage to the Readme as well?

2017-05-31 07:59 UTC, tobilg requested changes

2017-05-31 07:59 UTC, tobilg commented on index.js
> +    if (process.env.APP_ID_REGEXS.indexOf(",") > -1) {
Is splitting by `,` for regexes? Will only work it the regexes themselves don't contain a `,`

2017-05-31 07:59 UTC, tobilg commented on index.js
> +if (process.env.APP_ID_REGEXS) {
I'd suggest to call the env var `APP_ID_REGEXES`, see https://en.wiktionary.org/wiki/regex#Noun

2017-05-31 07:59 UTC, tobilg commented on index.js
> +        //console.log(JSON.stringify(data));
I'd like to encapsulate the filtering in the `lib/SlackHandler.js` file, not in the main `index.js`

2017-05-31 07:59 UTC, tobilg commented on index.js
> +function filterEventsByAppId(data){
Please move this to `lib/SlackHandler.js`

2017-05-31 07:59 UTC, tobilg commented on index.js
> +function sendSlackMessage(name, data){
Is this single-line function even necessary?

2017-05-31 08:04 UTC, tobilg commented
Do you also need an update of the DC/OS Universe package @eodgooch?

2017-05-31 20:36 UTC, eodgooch commented on index.js
> +if (process.env.APP_ID_REGEXS) {
haha of course

2017-05-31 20:37 UTC, eodgooch commented on index.js
> +function sendSlackMessage(name, data){
not necessary but my standard practice is to write a function if I'm writing the same line of code 2+ times.

2017-05-31 21:29 UTC, eodgooch commented on index.js
> +    if (process.env.APP_ID_REGEXS.indexOf(",") > -1) {
that's a great insight. I completely overlooked it. The intent was to allow a comma separated list of regex similar to your `EVENT_TYPES`.

2017-06-02 01:33 UTC, eodgooch commented
I'll go ahead and update the DC/OS package once you approve updates. What version tag? `0.3.2`?

I am also considering adding an env var to log events. Not sure if this is something you want in the project. My goal is to log events to get picked up by our shipper and sent to ES. Let me know.

2017-06-05 15:32 UTC, tobilg commented
I implemented the desired changes in https://github.com/tobilg/marathon-slack/commit/af88c18c77ed0563b90b660750df986c03b310fa The Docker image is currently building in version `0.4.0`.

2017-06-05 15:32 UTC, closed without merging